version: "3"

services:
  django:
    container_name: django19001-v2
    build:
      context: .
      dockerfile: django.Dockerfile
    # command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - postgres_db
    volumes:
      - ./avarus/:/avarus/
      - ./inf.py:/avarus/inf.py
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - app-tier
    env_file:
      - .env

  postgres_db:
    image: postgres:16.2-bookworm
    container_name: postgres19001-v2
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - app-tier
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  app-tier:
    driver: bridge
