# Generated by Django 3.2.25 on 2024-04-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Location name')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_locations', to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ('-id',),
            },
        ),
    ]
