# Generated by Django 3.2.25 on 2024-04-22 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0001_initial'),
        ('map_locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Location name')),
                ('authors', models.CharField(max_length=120, null=True, verbose_name='Authors')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
            ],
            options={
                'verbose_name': 'Location',
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
    ]
