# Generated by Django 3.2.25 on 2024-04-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0002_auto_20240422_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='photo',
            field=models.FileField(blank=True, upload_to='pictures'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='plots',
            field=models.CharField(max_length=120, null=True, verbose_name='Number of plots'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='url_page',
            field=models.CharField(max_length=120, null=True, verbose_name='URL page'),
        ),
        migrations.AddField(
            model_name='maplocation',
            name='url_photo',
            field=models.CharField(max_length=120, null=True, verbose_name='URL photo'),
        ),
    ]
