# Generated by Django 3.2.25 on 2024-04-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0003_auto_20240422_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='num',
            field=models.CharField(max_length=120, null=True, verbose_name='Number'),
        ),
    ]
