# Generated by Django 3.2.25 on 2024-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_locations', '0004_maplocation_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplocation',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='latitude',
            field=models.CharField(max_length=120, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='maplocation',
            name='longitude',
            field=models.CharField(max_length=120, null=True, verbose_name='Longitude'),
        ),
    ]
