# Generated by Django 3.2.25 on 2024-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.TextField(blank=True, help_text='Abstract', max_length=1000)),
                ('long_description', models.TextField(blank=True, help_text='Abstract', max_length=1000)),
            ],
            options={
                'verbose_name': 'Related Project',
            },
        ),
    ]
