# Generated by Django 3.2.25 on 2024-04-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedproject',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
