# Generated by Django 3.2.25 on 2024-04-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_projects', '0002_relatedproject_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedproject',
            name='url_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
