# Generated by Django 3.2.25 on 2024-04-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('related_projects', '0003_relatedproject_url_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedproject',
            name='long_description',
            field=models.TextField(blank=True, help_text="Long description that is discplayed on this project's page."),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description that is displayed on the all-projects page.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='title',
            field=models.CharField(blank=True, help_text='Title of the project.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='url',
            field=models.URLField(blank=True, help_text='URL of the project.', null=True),
        ),
        migrations.AlterField(
            model_name='relatedproject',
            name='url_text',
            field=models.CharField(blank=True, help_text='Masking text for URL.', max_length=200, null=True),
        ),
    ]
