# Generated by Django 3.2.25 on 2024-04-22 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('abstract', models.TextField(blank=True, help_text='Abstract', max_length=1000)),
                ('authors', models.ManyToManyField(related_name='publications', to='authors.Author')),
            ],
            options={
                'verbose_name': 'Publication',
            },
        ),
    ]
